### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by SomeBrujah** [mohamedfrindi/TxtAnime.js#4]
Hi @mohamedfrindi ✋, there was an error when using your text animation package. There is an error when the text is 1 character long. To fix it, just add the following to the code: 
![image](https://user-images.githubusercontent.com/47982319/193020411-8e85f865-b377-44ac-b52b-76a15f7145df.png)

**Comment by mohamedfrindi** [comment]
@SomeBrujah  Thank you for your contribution
The problem has been resolved in [**v1.5.0**](https://github.com/mohamedfrindi/TxtAnime.js/tree/v1.5.0) 👍
