### ISSUE TITLE
Stop animation

### ISSUE THREAD

**Issue by SomeBrujah** [mohamedfrindi/TxtAnime.js#5]
@mohamedfrindi hello!) I need a help
How to stop animation when i want to change it with another one?
Now, when you change animation with another - Animations are superimposed on each other. Let's think how to fix it.

- Sincerely, Maxym

**Comment by mohamedfrindi** [comment]
@SomeBrujah 
To turn off the animation, add :
```
new TxtAnime(".element" , {
    repeat : false
})
```
The animation will be triggered once

**Comment by SomeBrujah** [comment]
> @SomeBrujah 
> To turn off the animation, add :
> ```
> new TxtAnime(".element" , {
>     repeat : false
> })
> ```
> The animation will be triggered once

And if the animation will be turning with repeat: true, how i can stop it. For example: I start some infinite animation, and I want to change it with another (Without page reload). What do I need? Animation start some setInterval, and i cannot clear it. In case with first 3 animation, I even cannot see this interval.
@mohamedfrindi

**Comment by SomeBrujah** [comment]
@mohamedfrindi 
My React application switches animations for one dom-element, and they start overlapping each other. How to solve it if I can't apply repeat = false

**Comment by mohamedfrindi** [comment]
@SomeBrujah 
In what effect do you face this problem ??

**Comment by SomeBrujah** [comment]
@mohamedfrindi hello
I have a React application, I have a component in which I call a function that calls your library with the necessary parameters.  When I switch the animation, that is, I call the function again but with different parameters, the animations start to overlap.  And accordingly, on 1 house-element, several animations begin to play. All of these animation i need to call with "repeat:true"

**Comment by mohamedfrindi** [comment]
@SomeBrujah 
The problem has been fixed in [v1.5.3](https://github.com/mohamedfrindi/TxtAnime.js/tree/v1.5.3) update

**Comment by SomeBrujah** [comment]
@mohamedfrindi thank you 🙏🏻
